import { useEffect, useRef, useState } from "react";
import { Link, useNavigate, useSearch } from "@tanstack/react-router";
import { ArrowRight, ArrowUp, Check, ChevronDown, Copy, Paperclip, X } from "lucide-react";
import { recordedAnswers } from "@/data/ask-fixtures";
import { askDesk, type AskAnswer, type AskAttachment, type ConnectResult, type TmsConnection } from "@/lib/api";
import { loadChats, newChatId, saveChat, type ChatEntry, type SavedChat } from "@/lib/chat-store";
import { Badge, Button, Card, Tooltip } from "@/components/ui";
import { useApp } from "./app-context";
import { ModeBadge, SectionHead } from "./operations-pages";
import { ConnectPreview } from "./tms-pages";

const recordedQuestions = Object.keys(recordedAnswers);
const readable = new Set(["csv","tsv","json","eml","txt","md","xml","edi"]);
function findRecorded(q: string): AskAnswer | undefined { const key = recordedQuestions.find(k => k.toLowerCase() === q.trim().toLowerCase()); return key ? (recordedAnswers as unknown as Record<string, AskAnswer>)[key] : undefined }

export function AskPage() {
  const { run, selectedScenario, connection } = useApp(); const search = useSearch({ strict: false }) as { q?: string; chat?: string }; const navigate = useNavigate();
  const [chatId, setChatId] = useState(search.chat ?? ""); const [thread, setThread] = useState<ChatEntry[]>([]); const [text, setText] = useState(""); const [files, setFiles] = useState<File[]>([]); const [busy, setBusy] = useState(false); const [drag, setDrag] = useState(false); const [notice, setNotice] = useState("");
  const [examples, setExamples] = useState<string[]>(() => ((run as unknown as { examples?: string[] }).examples ?? recordedQuestions).slice(0,6));
  const inputRef = useRef<HTMLTextAreaElement>(null); const fileRef = useRef<HTMLInputElement>(null); const endRef = useRef<HTMLDivElement>(null); const initialized = useRef(false);
  useEffect(() => { const found = search.chat ? loadChats().find(x => x.id === search.chat) : undefined; setChatId(search.chat ?? ""); setThread(found?.entries ?? []); setText(""); setFiles([]); initialized.current = true; requestAnimationFrame(() => inputRef.current?.focus()) }, [search.chat]);
  useEffect(() => { if (initialized.current && chatId && thread.length) saveChat({ id: chatId, title: chatTitle(thread), updatedAt: new Date().toISOString(), entries: thread }) }, [chatId, thread]);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: "smooth", block: "nearest" }); if (!busy) inputRef.current?.focus() }, [thread, busy]);
  useEffect(() => { if (search.q) { void ask(search.q, []); void navigate({ to: "/", search: search.chat ? { chat: search.chat } : {}, replace: true }) } }, [search.q]);
  function addFiles(list: FileList | File[]) { const next = Array.from(list); const tooBig = next.find(f => f.size > 1024 * 1024); if (tooBig) { setNotice(`${tooBig.name} is larger than 1 MB.`); return } const merged = [...files, ...next].slice(0,3); setFiles(merged); setNotice(files.length + next.length > 3 ? "Up to 3 files can be attached." : "") }
  async function prepare(selected: File[]): Promise<AskAttachment[]> { return Promise.all(selected.map(async file => ({ name: file.name, content: readable.has(file.name.split(".").pop()?.toLowerCase() ?? "") ? await file.text() : null }))) }
  async function submit() { const attachments = await prepare(files); await ask(text, attachments) }
  async function ask(question: string, attachments: AskAttachment[] = []) {
    const q = question.trim(); if ((!q && !attachments.length) || busy) return;
    const id = newChatId(); const active = chatId || newChatId(); const pending = { id, question: q, attachments };
    if (!chatId) { saveChat({ id: active, title: q || attachments[0]?.name || "New chat", updatedAt: new Date().toISOString(), entries: [pending] }); setChatId(active); void navigate({ to: "/", search: { chat: active }, replace: true }) }
    setText(""); setFiles([]); setBusy(true); setThread(t => [...t, pending]);
    let entry: ChatEntry;
    try { const answer = await askDesk(q, (run as unknown as { scenario?: { id?: string } | null }).scenario?.id ?? selectedScenario, connection, attachments); if (answer.examples?.length) setExamples(answer.examples.slice(0,6)); entry = { id, question: q, attachments, answer } }
    catch { const rec = q ? findRecorded(q) : undefined; entry = rec ? { id, question: q, attachments, answer: rec, recorded: true } : { id, question: q, attachments, unreachable: true } }
    setThread(t => t.map(e => e.id === id ? entry : e)); setBusy(false);
  }
  const empty = thread.length === 0;
  return <div className={`chat-page ${empty ? "chat-empty" : ""}`} onDragEnter={e => { e.preventDefault(); setDrag(true) }} onDragOver={e => e.preventDefault()} onDragLeave={e => { if (e.currentTarget === e.target) setDrag(false) }} onDrop={e => { e.preventDefault(); setDrag(false); addFiles(e.dataTransfer.files) }}>
    {drag && <div className="chat-drop"><Paperclip className="size-6"/><span>Drop files for the desk</span></div>}
    {empty ? <div className="chat-welcome"><h2>What can the desk do for you?</h2><Composer text={text} setText={setText} files={files} setFiles={setFiles} busy={busy} notice={notice} inputRef={inputRef} fileRef={fileRef} addFiles={addFiles} submit={submit}/><ExampleChips examples={examples} ask={q => void ask(q)}/></div> : <><div className="chat-thread">{thread.map(entry => <ThreadEntry key={entry.id} entry={entry} onAsk={q => void ask(q)}/>) }<div ref={endRef}/></div><div className="chat-dock"><Composer text={text} setText={setText} files={files} setFiles={setFiles} busy={busy} notice={notice} inputRef={inputRef} fileRef={fileRef} addFiles={addFiles} submit={submit}/></div></>}
  </div>;
}
function chatTitle(entries: ChatEntry[]) { const first = entries[0]; return first?.question.trim() || first?.attachments[0]?.name || "New chat" }
function Composer({ text, setText, files, setFiles, busy, notice, inputRef, fileRef, addFiles, submit }:{ text:string; setText:(v:string)=>void; files:File[]; setFiles:(v:File[])=>void; busy:boolean; notice:string; inputRef:React.RefObject<HTMLTextAreaElement|null>; fileRef:React.RefObject<HTMLInputElement|null>; addFiles:(v:FileList|File[])=>void; submit:()=>Promise<void> }) { return <form onSubmit={e => { e.preventDefault(); void submit() }} className="chat-composer"><div className="flex flex-wrap gap-1.5">{files.map((f,i) => <span key={`${f.name}-${i}`} className="attachment-chip"><Paperclip className="size-3"/><span className="max-w-40 truncate">{f.name}</span><button type="button" aria-label={`Remove ${f.name}`} onClick={() => setFiles(files.filter((_,j) => i !== j))}><X className="size-3"/></button></span>)}</div><div className="flex items-end gap-2"><Button type="button" variant="ghost" className="size-10 shrink-0 rounded-full p-0" aria-label="Attach files" onClick={() => fileRef.current?.click()}><Paperclip className="size-4"/></Button><input ref={fileRef} type="file" multiple className="hidden" onChange={e => { if (e.target.files) addFiles(e.target.files); e.target.value = "" }}/><textarea ref={inputRef} value={text} onChange={e => { setText(e.target.value); e.target.style.height="0px"; e.target.style.height=`${Math.min(e.target.scrollHeight,160)}px` }} onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); void submit() } }} rows={1} aria-label="Ask the desk" placeholder="Ask the desk anything" className="min-h-10 min-w-0 flex-1 resize-none bg-transparent py-2.5 text-sm outline-none"/><Button type="submit" aria-label="Ask" disabled={(!text.trim() && !files.length) || busy} className="size-10 shrink-0 rounded-full p-0"><ArrowUp className="size-4"/></Button></div>{notice && <p className="px-12 text-xs text-state-amber">{notice}</p>}</form> }
function ExampleChips({examples,ask}:{examples:string[];ask:(q:string)=>void}) { return <div className="mt-4 flex flex-wrap justify-center gap-2">{examples.map(x => <button key={x} onClick={() => ask(x)} className="ask-chip">{x}</button>)}</div> }

function ThreadEntry({ entry, onAsk }: { entry: ChatEntry; onAsk: (q: string) => void }) {
  const a = entry.answer; const { applyConnection } = useApp(); const [preview, setPreview] = useState<ConnectResult | null>(a?.connection_preview ?? null); const [copied,setCopied]=useState(false); const [exact,setExact]=useState(false);
  async function usePreview() { if (!preview) return; const c: TmsConnection = { kind:"file", name:preview.name, source:preview.source, read_at:preview.read_at, bookings:preview.bookings, ...(preview.writeback_url !== undefined ? { writeback_url: preview.writeback_url } : {}) }; await applyConnection(c); setPreview(null) }
  return <article className="space-y-4"><div className="flex justify-end"><div className="max-w-[85%] rounded-2xl rounded-br-md bg-muted px-4 py-3 text-sm"><p className="break-words">{entry.question}</p>{entry.attachments.length > 0 && <div className="mt-2 flex flex-wrap gap-1.5">{entry.attachments.map((f,i)=><span key={`${f.name}-${i}`} className="attachment-chip"><Paperclip className="size-3"/>{f.name}</span>)}</div>}</div></div>
    {!a && !entry.unreachable && <div className="flex items-center gap-2"><Mark/><span className="typing-dot"/><span className="typing-dot"/><span className="typing-dot"/><span className="sr-only">The desk is answering</span></div>}
    {entry.unreachable && <div className="answer-row"><Mark/><div><p className="text-sm font-medium">The desk isn't reachable right now — nothing made up.</p><p className="mt-1 text-xs text-muted-foreground">These recorded questions still have answers:</p><div className="mt-3 flex flex-wrap gap-2">{recordedQuestions.map(q=><button key={q} onClick={()=>onAsk(q)} className="ask-chip">{q}</button>)}</div></div></div>}
    {a && <div className="answer-row answer-in"><Mark/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2">{a.answered && a.routed_to ? <><span className="worker-pill"><span className={`size-1.5 rounded-full bg-state-${a.routed_to.mode === "live" ? "green" : a.routed_to.mode === "scripted" ? "amber" : "blue"}`}/>{a.routed_to.name}<ModeBadge mode={a.routed_to.mode}/></span>{a.route_reason ? <Tooltip content={a.route_reason}><span className="cursor-help text-xs text-muted-foreground underline decoration-dotted">routed by {a.routed_by}</span></Tooltip> : <span className="text-xs text-muted-foreground">routed by {a.routed_by}</span>}{a.worded_by === "model" ? <><span className="text-xs text-muted-foreground">worded by a small model · facts checked</span>{a.plain_text && <Button variant="ghost" className="h-7 px-2 text-xs" onClick={()=>setExact(value=>!value)}>{exact?"Hide exact wording":"Show the desk's exact wording"}</Button>}</> : a.worded_by === "code" ? (a.wording_note ? <Tooltip title="Wording" content={a.wording_note}><span className="cursor-help text-xs text-muted-foreground underline decoration-dotted">desk's own wording</span></Tooltip> : <span className="text-xs text-muted-foreground">desk's own wording</span>) : null}</> : <Badge tone="amber">No Worker owns this</Badge>}{entry.recorded&&<Badge tone="amber">Recorded answer</Badge>}</div><p className="mt-4 break-words text-sm leading-6">{a.text}</p>{exact&&a.plain_text&&<div className="mt-3 rounded-lg border border-border bg-muted p-3 text-xs leading-5 text-muted-foreground">{a.plain_text}</div>}
      {a.facts.length>0&&<div className="mt-4 flex flex-wrap gap-2">{a.facts.map((f,i)=><span key={i} className="rounded-md border border-border bg-muted px-2 py-1 text-xs"><span className="text-muted-foreground">{f.label}</span> <b className="font-mono font-medium">{String(f.value)}</b></span>)}</div>}{a.links.length>0&&<div className="mt-4 flex flex-wrap gap-2">{a.links.map((l,i)=><AnswerLink key={i} link={l}/>)}</div>}
      {!a.answered&&a.suggestions.length>0&&<ul className="mt-4 space-y-2 text-sm">{a.suggestions.map((s,i)=>{const m=s.match(/["“]([^"”]+\?)["”]/);return <li key={i} className="flex flex-wrap items-center gap-2 text-muted-foreground"><span>{m?s.replace(m[0],"").trim():s}</span>{m&&<button className="ask-chip" onClick={()=>onAsk(m[1]??"")}>{m[1]}</button>}</li>})}</ul>}
      {a.conversation.length>0&&<details className="mt-5 border-t border-border pt-4"><summary className="flex cursor-pointer list-none items-center gap-2 text-xs font-medium text-muted-foreground"><ChevronDown className="size-3.5"/>How the desk answered ({a.conversation.length} messages)</summary><ol className="mt-3 space-y-2">{a.conversation.map(m=>{const row=<li className="rounded-lg border border-border p-3"><div className="flex flex-wrap items-center gap-2 text-xs"><span className="flex size-5 items-center justify-center rounded-full bg-primary font-mono text-[9px] text-primary-foreground">{m.seq}</span><b>{m.from}</b><ArrowRight className="size-3 text-muted-foreground"/><span>{m.to}</span><Badge>{m.kind}</Badge></div><p className="mt-2 break-words text-xs leading-5 text-muted-foreground">{m.text}</p></li>;return m.why?<Tooltip key={m.seq} content={m.why}>{row}</Tooltip>:<div key={m.seq}>{row}</div>})}</ol></details>}
      {preview&&<ConnectPreview p={{result:preview}} onUse={()=>void usePreview()} onCancel={()=>setPreview(null)} dismissLabel="Dismiss"/>}
      {a.desk_item?.outputs&&a.desk_item.outputs.length>0&&<div className="mt-5 border-t border-border pt-4"><SectionHead title="Desk outputs"/>{a.desk_item.outputs.map((o,i)=><Card key={i} className="mb-2 p-3"><div className="flex flex-wrap items-center justify-between gap-2 text-xs"><b>{o.worker}</b>{o.status&&<Badge tone={o.status.toLowerCase().includes("queued")?"blue":"amber"}>{o.status}</Badge>}</div><p className="mt-2 text-sm">{o.subject??o.action}</p></Card>)}<Link to="/approvals" search={{booking:undefined,kind:undefined,agent:undefined,severity:undefined,age:undefined,sort:undefined}} className="text-sm font-medium hover:underline">Review in Approvals →</Link></div>}
      {a.checked_against?.note&&<p className="mt-4 text-xs text-muted-foreground">{a.checked_against.note}</p>}<Button variant="ghost" className="mt-2 h-8 px-2" onClick={()=>{try{void navigator.clipboard.writeText(a.text);setCopied(true);setTimeout(()=>setCopied(false),1500)}catch{}}}>{copied?<Check className="size-3.5"/>:<Copy className="size-3.5"/>}{copied?"Copied":"Copy"}</Button></div></div>}
  </article>;
}
function Mark(){return <span className="mt-0.5 flex size-7 shrink-0 items-center justify-center bg-primary text-[9px] font-semibold text-primary-foreground">SQ</span>}
function AnswerLink({link}:{link:AskAnswer["links"][number]}){const cls="inline-flex h-8 items-center gap-1.5 rounded-lg border border-border bg-card px-3 text-xs font-medium hover:bg-muted";const inner=<>{link.label}<ArrowRight className="size-3"/></>;const search=link.id?{id:link.id}:{};switch(link.view){case"shipments":return <Link to="/shipments" search={search} className={cls}>{inner}</Link>;case"desk":return <Link to="/desk" search={search} className={cls}>{inner}</Link>;case"approvals":return <Link to="/approvals" search={{booking:undefined,kind:undefined,agent:undefined,severity:undefined,age:undefined,sort:undefined}} className={cls}>{inner}</Link>;case"risk":return <Link to="/risk" className={cls}>{inner}</Link>;case"tms":return <Link to="/tms" className={cls}>{inner}</Link>;default:return null}}

export function DeskToday(){const{workflow}=useApp();const s=workflow.stats as unknown as{items?:number;routed?:number;playbook_fixes?:number;escalations?:number;mails?:number};const tmsQueued=workflow.outputs.filter(o=>o.kind==="tms").length;const flow:Array<[string,number|undefined]>=[["Inbox",s.items],["Workers",s.routed],["Playbook check",s.playbook_fixes],["Your approval",workflow.outputs.length],["TMS",tmsQueued]];const stats:Array<[string,number|undefined]>=[["Mails in",s.items],["Routed",s.routed],["Escalated",s.escalations],["Drafts",s.mails],["TMS changes queued",tmsQueued],["Playbook fixes",s.playbook_fixes]];return <Card className="p-5"><div className="flex items-start justify-between gap-3"><SectionHead title="The desk today" caption="The inbox worked by the Workers"/><Link to="/desk" className="shrink-0 text-xs font-medium hover:underline">Open the desk →</Link></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{stats.map(([l,v])=><div key={l} className="rounded-lg bg-muted p-3"><p className="text-[10px] font-semibold uppercase text-muted-foreground">{l}</p><p className="mt-1 font-mono text-xl font-semibold">{v??"—"}</p></div>)}</div><div className="mt-5 flex flex-wrap items-center gap-1.5 text-xs">{flow.map(([l,v],i)=><span key={l} className="flex items-center gap-1.5"><span className="rounded-md border border-border px-2 py-1">{l} <b className="font-mono">{v??"—"}</b></span>{i<flow.length-1&&<ArrowRight className="size-3 text-muted-foreground"/>}</span>)}</div></Card>}
export function TmsStatusCard(){const{run,connection}=useApp();const t=run.tms as typeof run.tms&{read_at?:string|null};const readAt=t.read_at??(connection?.kind==="file"?connection.read_at:null);return <Card className="p-5"><div className="flex items-start justify-between gap-3"><SectionHead title="TMS connection" caption={t.honesty}/><Badge tone={connection?"green":"blue"}>{connection?"Connected":"DEMO"}</Badge></div><dl className="grid grid-cols-2 gap-3 text-xs"><div><dt className="text-muted-foreground">Connector</dt><dd className="mt-1 break-words font-medium">{t.connector}</dd></div><div><dt className="text-muted-foreground">Status</dt><dd className="mt-1 font-medium">{t.status}</dd></div><div><dt className="text-muted-foreground">Bookings read</dt><dd className="mt-1 font-mono">{t.bookings_read}</dd></div><div><dt className="text-muted-foreground">Changes queued</dt><dd className="mt-1 font-mono">{t.queued}</dd></div>{readAt&&<div className="col-span-2"><dt className="text-muted-foreground">Last read</dt><dd className="mt-1 font-mono">{new Date(readAt).toLocaleString([],{dateStyle:"medium",timeStyle:"short"})}</dd></div>}</dl><Link to="/tms" className="mt-5 inline-flex h-9 items-center rounded-lg bg-primary px-3 text-sm font-medium text-primary-foreground">{connection?"Manage":"Connect your TMS"}</Link></Card>}