import { useEffect, useState, type ReactNode } from "react";
import { Link } from "@tanstack/react-router";
import { Check, Copy, Plug } from "lucide-react";
import { Badge, Button, Card } from "@/components/ui";
import { getVerification } from "@/lib/connection-verification";
import { hostOf } from "@/lib/api";
import { useApp } from "./app-context";
import { ConnectionTest } from "./tms-pages";
const MCP_URL="https://www.sqrlane.com/mcp";
export function ConnectionsPage(){const {run,connection}=useApp();const [copied,setCopied]=useState(false);const [tick,setTick]=useState(0);useEffect(()=>{const fn=()=>setTick(x=>x+1);addEventListener("sqrlane-verification",fn);return()=>removeEventListener("sqrlane-verification",fn)},[]);void tick;const risk=run.risk as typeof run.risk&{families?:string[]};const tmsVerification=connection?.kind==="api"?getVerification("api",connection.url):undefined;const wbVerification=getVerification("writeback",connection?.writeback_url);return <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
  <ConnectionCard title="Your TMS" status={!connection?"Demo":tmsVerification?"Connected":"Configured — not verified"} tone={!connection?"blue":tmsVerification?"green":"neutral"}><p>{run.tms.connector}</p><p className="text-muted-foreground">{run.tms.status}</p>{tmsVerification&&<p className="text-state-green">Verified {formatVerified(tmsVerification.verified_at)}</p>}{connection?.kind==="api"&&<ConnectionTest body={{kind:"api",url:connection.url,token:connection.token,auth_header:connection.auth_header,records_path:connection.records_path}}/>}<PageLink to="/tms">{connection?"Manage":"Connect"}</PageLink></ConnectionCard>
  <ConnectionCard title="Write-back" status={!connection?.writeback_url?"Not connected":wbVerification?"Connected":"Configured — not verified"} tone={wbVerification?"green":"neutral"}><p>{connection?.writeback_url?hostOf(connection.writeback_url):"Not set — approved changes are exported"}</p>{wbVerification&&<p className="text-state-green">Verified {formatVerified(wbVerification.verified_at)}</p>}{connection?.writeback_url&&<ConnectionTest body={{kind:"writeback",url:connection.writeback_url,token:connection.token,auth_header:connection.auth_header}}/>}<PageLink to="/tms">Open TMS link</PageLink></ConnectionCard>
  <ConnectionCard title="Mailbox (Outlook / Gmail)" status="Not connected" tone="neutral"><p>No mailbox is connected in this build. Drop a mail (.eml) into Home and the desk works it like any inbound mail.</p><PageLink to="/">Try it on Home</PageLink></ConnectionCard>
  <ConnectionCard title="Claude (MCP)" status="Available" tone="blue"><p>Add {MCP_URL} as a custom connector in Claude.</p><div className="flex min-w-0 items-center gap-2 rounded-lg border border-border bg-muted p-1 pl-3"><code className="min-w-0 flex-1 truncate font-mono text-xs">{MCP_URL}</code><Button variant="outline" className="h-8 shrink-0" onClick={()=>{try{void navigator.clipboard.writeText(MCP_URL);setCopied(true);setTimeout(()=>setCopied(false),1500)}catch{}}}>{copied?<Check className="size-3.5"/>:<Copy className="size-3.5"/>}{copied?"Copied":"Copy"}</Button></div><div className="flex flex-wrap gap-1.5">{["ask_sqrlane","list_bookings","list_scenarios"].map(x=><span key={x} className="rounded-md border border-border px-2 py-1 font-mono text-xs">{x}</span>)}</div></ConnectionCard>
  <ConnectionCard title="Risk sources" status={risk.live_sources_read>0?"Connected":"Not connected"} tone={risk.live_sources_read>0?"green":"neutral"}><p><span className="font-mono">{risk.live_sources_read}</span> of <span className="font-mono">{risk.live_sources_total}</span> sources read on the last run</p>{risk.live_sources_read===0&&<p className="text-muted-foreground">Not read yet — press Run</p>}{risk.families?.length?<div className="flex flex-wrap gap-1.5">{risk.families.map(x=><Badge key={x}>{x}</Badge>)}</div>:null}</ConnectionCard>
  <ConnectionCard title="AI model" status={run.ai?.model?"Connected":"Demo"} tone={run.ai?.model?"green":"blue"}><p className="font-mono">{run.ai?.model??"Rules only"}</p>{run.ai?.provider&&<p className="text-muted-foreground">{run.ai.provider}</p>}</ConnectionCard>
 </div>}
function formatVerified(value:string){return new Date(value).toLocaleString([],{dateStyle:"medium",timeStyle:"short"})}
function ConnectionCard({title,status,tone,children}:{title:string;status:string;tone:"green"|"blue"|"neutral";children:ReactNode}){return <Card className="flex min-h-56 flex-col p-5"><div className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-muted"><Plug className="size-4"/></span><Badge tone={tone}>{status}</Badge></div><h2 className="mt-5 text-sm font-semibold">{title}</h2><div className="mt-2 flex flex-1 flex-col gap-3 text-xs leading-5">{children}</div></Card>}
function PageLink({to,children}:{to:"/"|"/tms";children:ReactNode}){return <Link to={to} className="mt-auto inline-flex w-fit items-center text-sm font-medium hover:underline">{children} →</Link>}
