import { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import { Check, Circle, ExternalLink, X } from "lucide-react";
import { recordedInsights } from "@/data/ask-fixtures";
import { recordedMap } from "@/data/map-fixture";
import { ageLabel, approvalRows, severityRank } from "@/lib/approval-data";
import { getVerification } from "@/lib/connection-verification";
import { getInsights, getMap, type InsightsData, type MapData, type ScenarioId } from "@/lib/api";
import { sourceName, toneFor } from "@/lib/presentation";
import { loadOnboarding, updateOnboarding, type OnboardingState } from "@/lib/onboarding";
import { loadApprovalLog } from "@/lib/approval-log";
import { Badge, Button, Card, Tooltip } from "@/components/ui";
import { useApp } from "./app-context";
import { MapCanvas } from "./map-page";
import { SectionHead, StatCard } from "./operations-pages";
import { eur, RunwayCard } from "./analytics-components";

export function DashboardPage() {
  const { run, workflow, approved, selectedScenario, connection, runChanges } = useApp();
  const scenario = (run as unknown as { scenario?: { id?: ScenarioId; name?: string } | null }).scenario?.id ?? selectedScenario;
  const [data, setData] = useState<InsightsData>(recordedInsights as InsightsData);
  const [map, setMap] = useState<MapData>(recordedMap);
  const [recorded, setRecorded] = useState(false);
  const [onboarding, setOnboarding] = useState<OnboardingState>(() => loadOnboarding());
  const load = useCallback(async () => { try { setData(await getInsights(scenario, connection)); setRecorded(false); } catch { setData(recordedInsights as InsightsData); setRecorded(true); } }, [scenario, connection]);
  const loadMap = useCallback(async () => { try { setMap(await getMap(scenario, connection)); } catch { setMap(recordedMap); } }, [scenario, connection]);
  useEffect(() => { void load(); void loadMap(); }, [load, loadMap]);
  useEffect(() => { const timer = window.setInterval(() => void loadMap(), 60000); return () => window.clearInterval(timer); }, [loadMap]);
  useEffect(() => { const refresh=()=>setOnboarding(loadOnboarding()); addEventListener("sqrlane-onboarding",refresh); return()=>removeEventListener("sqrlane-onboarding",refresh); }, []);
  useEffect(() => { if(connection) updateOnboarding({connection:true}); }, [connection]);
  useEffect(() => { const patch:Partial<OnboardingState>={scenario:true};if(run.ran_at)patch.run=true;if(loadApprovalLog().length)patch.change=true;updateOnboarding(patch); }, [run.ran_at]);
  const rows = useMemo(() => approvalRows(run, workflow), [run, workflow]);
  const waiting = rows.filter(row => !approved.has(row.key));
  const exposure = useMemo(() => new Map(data.at_stake.rows.map(row => [row.id, row.stay_exposure_eur ?? 0])), [data.at_stake.rows]);
  const grouped = Object.values(waiting.reduce<Record<string, typeof waiting>>((all, row) => { (all[row.booking] ??= []).push(row); return all; }, {})).sort((a, b) => severityRank(groupSeverity(b)) - severityRank(groupSeverity(a)) || (exposure.get(b[0]?.booking ?? "") ?? 0) - (exposure.get(a[0]?.booking ?? "") ?? 0) || oldestTime(a) - oldestTime(b)).slice(0,6);
  const tmsVerified = connection?.kind === "api" ? getVerification("api", connection.url) : undefined;
  const scenarioName = (run as unknown as { scenario?: { name?: string } | null }).scenario?.name ?? run.scenarios.find(s=>s.id===selectedScenario)?.name ?? "Calm board";
  const complete = onboarding.scenario&&onboarding.connection&&onboarding.run&&onboarding.decision&&onboarding.change;
  const showChecklist = !complete && !onboarding.dismissed;
  const checklist: Array<{key:keyof Omit<OnboardingState,"dismissed">;label:string;to:"/overview"|"/connections"|"/shipments"|"/approvals"}> = [
    {key:"scenario",label:"Pick a scenario",to:"/overview"},{key:"connection",label:"Check the TMS connection",to:"/connections"},{key:"run",label:"Run the desk",to:"/overview"},{key:"decision",label:"Open one decision",to:"/shipments"},{key:"change",label:"Approve or export one change",to:"/approvals"},
  ];
  const missed = data.customers.rows.filter(row => row.breaks_date).length;
  const stillBreaks = data.runway.rows.filter(row => row.status === "breaks").length;
  return <div className="space-y-5">
    {recorded && <div className="flex justify-end"><Badge tone="amber">Recorded</Badge></div>}
    {showChecklist ? <Card className="p-4"><div className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-3"><div className="min-w-0"><h2 className="text-sm font-semibold">Get started in five steps</h2><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-5">{checklist.map(step=><Link key={step.key} to={step.to} className="flex min-h-10 items-center gap-2 rounded-lg border border-border px-3 py-2 text-xs font-medium hover:bg-muted">{onboarding[step.key]?<Check className="size-4 shrink-0 text-state-green"/>:<Circle className="size-4 shrink-0 text-muted-foreground"/>}<span>{step.label}</span></Link>)}</div></div><Button variant="ghost" className="size-10 shrink-0 p-0" aria-label="Dismiss getting started" onClick={()=>updateOnboarding({dismissed:true})}><X className="size-4"/></Button></div></Card> : !complete && <div className="flex justify-end"><button className="min-h-10 text-xs font-medium text-muted-foreground underline decoration-dotted hover:text-foreground" onClick={()=>updateOnboarding({dismissed:false})}>Show getting started</button></div>}
    <Card className="grid gap-0 overflow-hidden sm:grid-cols-2 xl:grid-cols-4"><StateLink to="/overview" label="Scenario" value={scenarioName}/><StateLink to="/connections" label="TMS" value={!connection?"Demo":tmsVerified?`${run.tms.connector} · ${run.tms.status}`:`${run.tms.connector} · Configured — not verified`} dot={!connection||!!tmsVerified}/><StateLink to="/overview" label="Last run" value={run.ran_at?new Date(run.ran_at).toLocaleString([], {dateStyle:"medium",timeStyle:"short"}):"Not run yet"}/><StateLink to="/agents" label="Decision engine" value={run.ai?.model??"rules"}/></Card>
    {runChanges !== null && <Card className="p-5"><SectionHead title="What changed since your last run" caption="Compared with your previous run in this browser."/>{runChanges.length?<ul className="grid gap-2 md:grid-cols-2">{runChanges.map(change=><li key={change.key} className="rounded-lg bg-muted px-3 py-2 text-xs font-medium">{change.text}</li>)}</ul>:<p className="text-xs text-muted-foreground">No booking states or disruptions changed.</p>}</Card>}
    <div className="stat-grid"><Link to="/approvals" search={{}}><StatCard label="Bookings needing a decision" value={data.decisions.bookings} caption={data.decisions.caption} tone="amber"/></Link><a href="#at-stake"><StatCard label="At stake if nothing is done" value={eur(data.at_stake.total_stay_eur)} caption={`${eur(data.at_stake.total_avoided_eur)} avoided by the recommended actions`} tone="red"/></a><a href="#customers"><StatCard label="Customers to notify" value={data.customers.rows.length} caption={`${missed} with a missed date`} tone="amber"/></a><a href="#runway"><StatCard label="Still misses its date" value={stillBreaks} caption="After the recommended decision" tone="red"/></a></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.65fr)_minmax(300px,1fr)]">
      <div id="at-stake"><AtStakeCard data={data}/></div><div id="customers"><CustomersCard data={data}/></div>
    </div>
    <Card className="overflow-hidden"><div className="p-5"><SectionHead title="Which bookings need a decision?" caption="Highest severity, then exposure, then oldest queued"/></div>{grouped.length?grouped.map(group=><DecisionGroup key={group[0]?.booking??"unknown"} rows={group}/>):<p className="empty">Nothing waiting for you.</p>}</Card>
    <div id="runway"><RunwayCard section={data.runway}/></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]"><Card className="min-w-0 p-5"><div className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-3"><SectionHead title="Where are the affected bookings?" caption={`Monitoring ${map.mapped} of ${map.bookings} mapped bookings every 60 seconds`}/><Link to="/map" className="inline-flex shrink-0 items-center gap-1 text-xs font-medium">Open map <ExternalLink className="size-3"/></Link></div><MapCanvas data={map} compact/></Card><Card className="p-5"><SectionHead title="Which disruptions are active?"/>{run.risk.events.length?run.risk.events.map(event=>{const moved=run.shipments.filter(s=>(s.decision.triggering_events as readonly string[]??[]).includes(event.event_id)).length;return <Link to="/risk" key={event.event_id} className="block border-t border-border py-4 first:border-0 first:pt-0"><div className="flex items-start justify-between gap-3"><p className="text-sm font-medium leading-5">{event.title}</p><Badge tone={toneFor(event.severity)}>{event.severity}</Badge></div><p className="mt-2 text-xs text-muted-foreground">{sourceName(event.source)} · {moved} bookings moved</p></Link>}):<p className="empty">Run a scenario to see disruptions here.</p>}</Card></div>
    <p className="text-xs text-muted-foreground">{data.note}</p>
  </div>;
}

function StateLink({to,label,value,dot}:{to:"/overview"|"/connections"|"/agents";label:string;value:string;dot?:boolean}){return <Link to={to} className="min-w-0 border-b border-border px-4 py-3 last:border-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><p className="stat-label">{label}</p><p className="mt-1 flex min-w-0 items-center gap-2 truncate text-xs font-medium">{dot&&<span className="size-1.5 shrink-0 rounded-full bg-state-green"/>}<span className="truncate">{value}</span></p></Link>}
function groupSeverity(rows: ReturnType<typeof approvalRows>) { return rows.reduce((max,row)=>severityRank(row.severity)>severityRank(max)?row.severity:max,"none"); }
function oldestTime(rows: ReturnType<typeof approvalRows>) { return Math.min(...rows.map(row=>row.queued_at?Date.parse(row.queued_at):Number.MAX_SAFE_INTEGER)); }
function DecisionGroup({rows}:{rows:ReturnType<typeof approvalRows>}){const drafts=rows.filter(r=>r.kind==="Email draft").length;const changes=rows.length-drafts;const severity=groupSeverity(rows);const oldest=rows.reduce<string|null>((m,r)=>!r.queued_at?m:!m||Date.parse(r.queued_at)<Date.parse(m)?r.queued_at:m,null);return <div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4 border-t border-border px-5 py-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs font-semibold">{rows[0]?.booking}</span>{severity!=="none"&&<Badge tone={toneFor(severity)}>{severity}</Badge>}</div><p className="mt-1 truncate text-xs text-muted-foreground">{changes} changes · {drafts} drafts · {ageLabel(oldest)}</p></div><Link to="/approvals" search={{booking:rows[0]?.booking??"unknown"}} className="inline-flex h-8 shrink-0 items-center rounded-lg border border-border bg-card px-3 text-xs font-medium">Review</Link></div>}
function AtStakeCard({data}:{data:InsightsData}){return <Card className="min-w-0 overflow-hidden"><div className="p-5"><SectionHead title="What is at stake?" caption={data.at_stake.subtitle}/></div><div className="table-wrap"><table><thead><tr><th>Booking</th><th>Customer</th><th>Decision</th><th>If nothing is done</th><th>With the decision</th><th>Avoided</th></tr></thead><tbody>{data.at_stake.rows.map(row=>{const unpriced=/not priced/i.test(row.costs_basis);return <tr key={row.id}><td><Link to="/approvals" search={{booking:row.id}} className="font-mono font-semibold">{row.id}</Link></td><td>{row.customer}</td><td><div className="flex items-center gap-2"><Badge tone={toneFor(row.decision)}>{row.decision}</Badge>{row.breaks_date&&<Badge tone="red">misses date</Badge>}</div></td>{([row.stay_exposure_eur,row.action_exposure_eur,row.avoided_eur] as Array<number|null>).map((value,index)=><td key={index} className={index===2?"font-semibold":""}>{unpriced?<Tooltip title="Cost basis" content={row.costs_basis}><span tabIndex={0}>—</span></Tooltip>:eur(value)}</td>)}</tr>})}<tr><td colSpan={3} className="font-semibold">Total</td><td>{eur(data.at_stake.total_stay_eur)}</td><td>{eur(data.at_stake.total_action_eur)}</td><td className="font-semibold">{eur(data.at_stake.total_avoided_eur)}</td></tr></tbody></table></div><p className="border-t border-border p-4 text-xs leading-5 text-muted-foreground">{data.at_stake.basis}</p></Card>}
function CustomersCard({data}:{data:InsightsData}){return <Card className="overflow-hidden"><div className="p-5"><SectionHead title="Who needs to hear from us?" caption={data.customers.subtitle}/></div><div className="divide-y divide-border">{data.customers.rows.map(row=><Link key={row.customer} to="/approvals" search={{booking:row.bookings[0]??""}} className="block px-5 py-4 hover:bg-muted"><div className="flex items-start justify-between gap-3"><p className="text-sm font-medium">{row.customer}</p>{row.breaks_date&&<Badge tone="red">date missed</Badge>}</div><div className="mt-2 flex flex-wrap items-center gap-2">{row.bookings.map(id=><span key={id} className="font-mono text-[10px] text-muted-foreground">{id}</span>)}<span className="text-xs text-muted-foreground">{row.drafts} {row.drafts===1?"draft":"drafts"} ready</span></div></Link>)}</div></Card>}