import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowRight, Check, ChevronDown, Circle, ExternalLink, X } from "lucide-react";
import { recordedMap } from "@/data/map-fixture";
import { ageLabel, approvalRows } from "@/lib/approval-data";
import { getVerification } from "@/lib/connection-verification";
import { getMap, type MapData, type ScenarioId, type TodayData } from "@/lib/api";
import { sourceName, stateLabel, toneFor } from "@/lib/presentation";
import { loadOnboarding, updateOnboarding, type OnboardingState } from "@/lib/onboarding";
import { loadApprovalLog } from "@/lib/approval-log";
import { Badge, Button, Card, Tooltip } from "@/components/ui";
import { useApp } from "./app-context";
import { MapCanvas } from "./map-page";
import { SectionHead, StatCard } from "./operations-pages";
import { eur, signedDays } from "./analytics-components";

type Filter = "all" | "decision" | "breaks" | "resolved" | "plan";
type Sort = "runway" | "stake" | "eta";
type Journey = TodayData["journey"]["rows"][number];
type Runway = TodayData["runway"]["rows"][number];
type Stake = TodayData["at_stake"]["rows"][number];

export function DashboardPage() {
  const { run, workflow, approved, selectedScenario, connection, runChanges } = useApp();
  const scenario = ((run as unknown as { scenario?: { id?: ScenarioId } | null }).scenario?.id ?? selectedScenario);
  const [map, setMap] = useState<MapData>(recordedMap);
  const [highlighted, setHighlighted] = useState<string | null>(null);
  const [filter, setFilter] = useState<Filter>("all");
  const [sort, setSort] = useState<Sort>("runway");
  const [expanded, setExpanded] = useState<string | null>(null);
  const [onboarding, setOnboarding] = useState<OnboardingState>(() => loadOnboarding());
  const rowRefs = useRef<Array<HTMLDivElement | null>>([]);
  const loadMap = useCallback(async () => { try { setMap(await getMap(scenario, connection)); } catch { setMap(recordedMap); } }, [scenario, connection]);
  useEffect(() => { void loadMap(); const timer=window.setInterval(()=>void loadMap(),60000); return()=>window.clearInterval(timer); }, [loadMap]);
  useEffect(() => { const refresh=()=>setOnboarding(loadOnboarding()); addEventListener("sqrlane-onboarding",refresh); return()=>removeEventListener("sqrlane-onboarding",refresh); }, []);
  useEffect(() => { if(connection) updateOnboarding({connection:true}); }, [connection]);
  useEffect(() => { const patch:Partial<OnboardingState>={scenario:true};if(run.ran_at)patch.run=true;if(loadApprovalLog().length)patch.change=true;updateOnboarding(patch); }, [run.ran_at]);

  const hasRun=Boolean(run.ran_at);
  const today=hasRun ? run.today : null;
  const approvalQueue=useMemo(()=>approvalRows(run,workflow).filter(row=>!approved.has(row.key)),[run,workflow,approved]);
  const decisionBookings=new Set(approvalQueue.map(row=>row.booking));
  const runwayById=new Map((today?.runway.rows??[]).map(row=>[row.id,row]));
  const stakeById=new Map((today?.at_stake.rows??[]).map(row=>[row.id,row]));
  const allRows=today?.journey.rows??[];
  const rows=allRows.filter(row=>filter==="all"||filter==="decision"&&decisionBookings.has(row.id)||filter==="breaks"&&runwayById.get(row.id)?.status==="breaks"||filter==="resolved"&&runwayById.get(row.id)?.status==="resolved"||filter==="plan"&&row.state==="green").sort((a,b)=>sort==="stake"?(stakeById.get(b.id)?.stay_exposure_eur??-1)-(stakeById.get(a.id)?.stay_exposure_eur??-1):sort==="eta"?Date.parse(a.voyage.revised_eta??a.voyage.eta)-Date.parse(b.voyage.revised_eta??b.voyage.eta):(runwayById.get(a.id)?.margin_after_decision_days??999)-(runwayById.get(b.id)?.margin_after_decision_days??999));
  const maxDays=Math.max(1,...(today?.runway.rows??[]).flatMap(row=>[row.slack_days,row.worst_delay_days,row.delay_after_decision_days]));
  const missed=today?.customers.rows.filter(row=>row.breaks_date).length??0;
  const breaks=today?.runway.rows.filter(row=>row.status==="breaks").length??0;
  const verified=connection?.kind==="api"?getVerification("api",connection.url):undefined;
  const engine=run.ai?.model?.startsWith("(")?"Chosen on first run":run.ai?.model??"Rules only";
  const complete=onboarding.scenario&&onboarding.connection&&onboarding.run&&onboarding.decision&&onboarding.change;
  const checklist=[{key:"scenario",label:"Pick a scenario",to:"/overview"},{key:"connection",label:"Check the TMS connection",to:"/connections"},{key:"run",label:"Run the desk",to:"/overview"},{key:"decision",label:"Open one decision",to:"/shipments"},{key:"change",label:"Approve or export one change",to:"/approvals"}] as const;
  const setKpiFilter=(next:Filter,id:string)=>{setFilter(next);document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"})};

  return <div className="space-y-6">
    {!complete&&!onboarding.dismissed&&<Card className="p-5"><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-3"><div><h2 className="text-sm font-semibold">Get started in five steps</h2><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-5">{checklist.map(step=><Link key={step.key} to={step.to} className="flex min-h-10 items-center gap-2 rounded-xl border border-border px-3 py-2 text-xs font-medium transition-colors hover:bg-muted">{onboarding[step.key]?<Check className="size-4 text-state-green"/>:<Circle className="size-4 text-muted-foreground"/>}{step.label}</Link>)}</div></div><Button variant="ghost" className="size-10 p-0" aria-label="Dismiss getting started" onClick={()=>updateOnboarding({dismissed:true})}><X className="size-4"/></Button></div></Card>}
    {!complete&&onboarding.dismissed&&<div className="flex justify-end"><Button variant="ghost" onClick={()=>updateOnboarding({dismissed:false})}>Show getting started</Button></div>}
    <Card className="grid overflow-hidden sm:grid-cols-3"><Status label="TMS" value={!connection?"Demo":verified?`${run.tms.connector} · ${run.tms.status}`:"Configured — not verified"} live={!connection||!!verified}/><Status label="Decision engine" value={engine}/><Status label="Sources read" value={`${run.risk.live_sources_read} of ${run.risk.live_sources_total}`}/></Card>
    {!today?<Card className="p-8 text-center"><h2 className="text-base font-semibold">Nothing at stake — no disruption on the board.</h2><p className="mt-2 text-sm text-muted-foreground">Pick a scenario and press Run.</p></Card>:<>
      <div className="stat-grid">
        <Kpi onClick={()=>setKpiFilter("decision","shipments-board")} label="Needs a decision" value={decisionBookings.size} caption={`${approvalQueue.length} approval items waiting`} tone="amber"/>
        <Kpi onClick={()=>setKpiFilter("all","at-stake")} label="At stake if nothing is done" value={eur(today.at_stake.total_stay_eur)} caption={`${eur(today.at_stake.total_avoided_eur)} avoided by the decisions`} tone="red"/>
        <Kpi onClick={()=>setKpiFilter("decision","customers")} label="Customers to notify" value={today.customers.rows.length} caption={`${missed} with a missed date`} tone="amber"/>
        <Kpi onClick={()=>setKpiFilter("breaks","shipments-board")} label="Still misses its date" value={breaks} caption="After the recommended decision" tone="red"/>
      </div>
      {runChanges!==null&&<Card className="p-5"><SectionHead title="What changed since your last run" caption="Compared with your previous run in this browser."/>{runChanges.length?<ul className="grid gap-2 md:grid-cols-2">{runChanges.map(change=><li key={change.key} className="rounded-xl bg-muted px-3 py-2 text-xs font-medium">{change.text}</li>)}</ul>:<p className="text-xs text-muted-foreground">No booking states or disruptions changed.</p>}</Card>}
      <Card id="shipments-board" className="overflow-hidden scroll-mt-32"><div className="p-5 sm:p-6"><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_auto]"><SectionHead title="The shipments board" caption={`${allRows.length} bookings from this run`}/><div className="flex flex-col gap-2 sm:flex-row"><div className="flex max-w-full overflow-x-auto rounded-xl bg-muted p-1" aria-label="Filter shipments">{([['all','All'],['decision','Needs a decision'],['breaks','Misses date'],['resolved','Resolved'],['plan','On plan']] as const).map(([key,label])=><Button key={key} variant={filter===key?"secondary":"ghost"} className="h-8 whitespace-nowrap px-3 text-[11px]" onClick={()=>setFilter(key)}>{label}</Button>)}</div><select className="form-control mt-0 h-10 sm:w-40" value={sort} onChange={event=>setSort(event.target.value as Sort)} aria-label="Sort shipments"><option value="runway">Runs out first</option><option value="stake">At stake</option><option value="eta">ETA</option></select></div></div></div>
        <div className="hidden border-y border-border bg-muted/50 px-5 py-2 text-[10px] font-semibold uppercase text-muted-foreground xl:grid xl:grid-cols-[220px_190px_120px_minmax(260px,1fr)_110px] xl:gap-5"><span>Booking</span><span>Voyage stage</span><span>Agent loop</span><span className="grid grid-cols-[1fr_62px] gap-3"><span className="flex justify-between"><span>Time runway</span><span>{maxDays}d</span></span><span>Margin</span></span><span className="text-right">At stake</span></div>
        <div className="divide-y divide-border">{rows.map((journey,index)=><ShipmentBoardRow key={journey.id} journey={journey} runway={runwayById.get(journey.id)} stake={stakeById.get(journey.id)} maxDays={maxDays} expanded={expanded===journey.id} approved={approvalQueue.every(row=>row.booking!==journey.id)} onToggle={()=>setExpanded(value=>value===journey.id?null:journey.id)} onHover={setHighlighted} rowRef={node=>{rowRefs.current[index]=node}} onKeyDown={event=>{if(event.key==="ArrowDown"||event.key==="ArrowUp"){event.preventDefault();const next=Math.max(0,Math.min(rows.length-1,index+(event.key==="ArrowDown"?1:-1)));rowRefs.current[next]?.focus()}if(event.key==="Enter"){event.preventDefault();setExpanded(value=>value===journey.id?null:journey.id)}}}/>)}</div>
      </Card>
      <div className="grid gap-6 xl:grid-cols-[minmax(0,1.7fr)_minmax(320px,1fr)]"><div id="at-stake" className="scroll-mt-32"><AtStakeCard today={today}/></div><div id="customers" className="scroll-mt-32"><CustomersCard today={today}/></div></div>
      <div className="grid gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]"><Card className="min-w-0 p-5 sm:p-6"><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-3"><SectionHead title="Where are the affected bookings?" caption={`Monitoring ${map.mapped} of ${map.bookings} mapped bookings every 60 seconds`}/><Link to="/map" className="inline-flex items-center gap-1 text-xs font-medium">Open map <ExternalLink className="size-3"/></Link></div><MapCanvas data={map} compact highlighted={highlighted} onHighlight={setHighlighted}/></Card><Card className="p-5 sm:p-6"><SectionHead title="Which disruptions are active?"/>{run.risk.events.length?run.risk.events.map(event=>{const moved=run.shipments.filter(s=>(s.decision.triggering_events??[]).includes(event.event_id)).length;return <Link to="/risk" key={event.event_id} className="block border-t border-border py-4 first:border-0 first:pt-0"><div className="flex items-start justify-between gap-3"><p className="text-sm font-medium leading-5">{event.title}</p><Badge tone={toneFor(event.severity)}>{event.severity}</Badge></div><p className="mt-2 text-xs text-muted-foreground">{sourceName(event.source)} · {moved} bookings moved</p></Link>}):<p className="empty">No active disruptions in this run.</p>}</Card></div>
    </>}
  </div>;
}

function Status({label,value,live}:{label:string;value:string;live?:boolean}){return <div className="min-w-0 border-b border-border px-5 py-3 last:border-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><p className="stat-label">{label}</p><p className="mt-1 flex items-center gap-2 truncate text-xs font-medium">{live&&<span className="size-1.5 rounded-full bg-state-green"/>}<span className="truncate">{value}</span></p></div>}
function Kpi({onClick,...props}:{onClick:()=>void;label:string;value:string|number;caption:string;tone:"amber"|"red"}){return <button onClick={onClick} className="min-w-0 text-left"><StatCard {...props}/></button>}
function ShipmentBoardRow({journey,runway,stake,maxDays,expanded,approved,onToggle,onHover,rowRef,onKeyDown}:{journey:Journey;runway?:Runway;stake?:Stake;maxDays:number;expanded:boolean;approved:boolean;onToggle:()=>void;onHover:(id:string|null)=>void;rowRef:(node:HTMLDivElement|null)=>void;onKeyDown:(event:React.KeyboardEvent<HTMLDivElement>)=>void}){
 const runShipment=useApp().run.shipments.find(item=>item.id===journey.id);const loop=journey.loop.map(step=>step.key==="approved"?{...step,done:approved}:step);const unpriced=stake&&/not priced/i.test(stake.costs_basis);return <div ref={rowRef} role="button" tabIndex={0} aria-expanded={expanded} className="group outline-none transition-colors hover:bg-muted/40 focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-inset" onClick={onToggle} onMouseEnter={()=>onHover(journey.id)} onMouseLeave={()=>onHover(null)} onFocus={()=>onHover(journey.id)} onBlur={()=>onHover(null)} onKeyDown={onKeyDown}><div className="grid gap-5 px-5 py-5 xl:grid-cols-[220px_190px_120px_minmax(260px,1fr)_110px] xl:items-center">
  <div className="min-w-0"><div className="flex items-center gap-2"><span className="font-mono text-xs font-semibold">{journey.id}</span><Badge tone={toneFor(journey.state)}>{stateLabel(journey.state)}</Badge></div><p className="mt-2 truncate text-sm font-medium">{journey.cargo}</p><p className="mt-1 truncate text-xs text-muted-foreground">{journey.customer}</p><p className="mt-1 text-[11px] text-muted-foreground">{journey.origin} <ArrowRight className="inline size-3"/> {journey.destination}</p></div>
  <Voyage journey={journey}/><LoopDots loop={loop}/><RunwayBar runway={runway} maxDays={maxDays}/><div className="flex items-center justify-between xl:block xl:text-right"><span className="stat-label xl:hidden">At stake</span><p className="font-mono text-sm font-semibold tabular-nums">{unpriced||!stake?"—":eur(stake.stay_exposure_eur)}</p><ChevronDown className={`ml-auto mt-2 size-4 text-muted-foreground transition-transform ${expanded?"rotate-180":""}`}/></div>
 </div>{expanded&&<div className="border-t border-border bg-muted/30 px-5 py-5" onClick={event=>event.stopPropagation()}><div className="grid gap-5 lg:grid-cols-3"><div><p className="stat-label">Decision</p><p className="mt-2 text-sm font-semibold">{runShipment?.decision.headline??stake?.headline??"On plan"}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{runShipment?.decision.reasoning}</p></div><div><p className="stat-label">Cost comparison</p><p className="mt-2 text-xs">Nothing done <b>{unpriced?"—":eur(stake?.stay_exposure_eur)}</b></p><p className="mt-2 text-xs">With decision <b>{unpriced?"—":eur(stake?.action_exposure_eur)}</b></p></div><div><p className="stat-label">Waiting at the gate</p><p className="mt-2 text-xs">{runShipment?.drafts.length??0} drafted mails · {useApp().run.tms.writebacks.filter(item=>item.booking_ref===journey.id).length} queued changes</p><div className="mt-4 flex flex-wrap gap-2"><Link to="/approvals" search={{booking:journey.id}} className="inline-flex min-h-10 items-center rounded-xl bg-primary px-4 text-xs font-medium text-primary-foreground">Review in Approvals</Link><Link to="/map" search={{id:journey.id}} className="inline-flex min-h-10 items-center rounded-xl border border-border px-4 text-xs font-medium">Open on map</Link></div></div></div></div>}</div>
}
function Voyage({journey}:{journey:Journey}){const progress=Math.round(journey.voyage.progress*100);return <Tooltip title="Voyage basis" content={journey.voyage.basis}><div tabIndex={0}><div className="flex justify-between text-[9px] text-muted-foreground"><span>Booked</span><span>Departed</span><span>At sea</span><span>Arriving</span></div><div className="relative mt-2 h-1.5 rounded-full bg-muted"><span className="absolute inset-y-0 left-0 rounded-full bg-state-blue" style={{width:`${Math.max(2,progress)}%`}}/></div><p className="mt-2 text-[11px] text-muted-foreground">{progress}% of the voyage · ETA in {journey.voyage.days_to_eta}d</p>{journey.voyage.revised_eta?<p className="mt-1 text-[11px]"><s className="text-muted-foreground">{journey.voyage.eta}</s> → <b>{journey.voyage.revised_eta}</b></p>:<p className="mt-1 text-[11px]">ETA {journey.voyage.eta}</p>}</div></Tooltip>}
function LoopDots({loop}:{loop:Journey["loop"]}){return <div><div className="flex items-center justify-between">{loop.map((step,index)=><Tooltip key={step.key} title={step.label} content={step.detail}><span tabIndex={0} className={`flex size-5 items-center justify-center rounded-full border text-[9px] ${step.done===true?"border-state-green bg-state-green-soft text-state-green":step.done===false?"border-transparent text-muted-foreground":"border-border text-muted-foreground"}`}>{step.done===false?"–":step.done===true?"✓":index+1}</span></Tooltip>)}</div><p className="mt-2 text-[10px] text-muted-foreground">Detected · Decided · Drafted · Queued · Approved</p></div>}
function RunwayBar({runway,maxDays}:{runway?:Runway;maxDays:number}){if(!runway)return <span className="text-xs text-muted-foreground">Not provided</span>;const pct=(n:number)=>`${Math.min(100,n/maxDays*100)}%`;const noDelay=runway.worst_delay_days<=0&&runway.delay_after_decision_days<=0;return <div className="grid grid-cols-[minmax(0,1fr)_62px] items-center gap-3"><div><div className="relative h-7 overflow-visible rounded-lg bg-state-red-soft"><span className="absolute inset-y-0 left-0 rounded-lg bg-state-green-soft" style={{width:pct(runway.slack_days)}}/>{runway.worst_delay_days>0&&<Tooltip title="If nothing is done" content={`${runway.worst_delay_days}d delay`}><span tabIndex={0} className="absolute top-0 -translate-x-1/2 text-[12px] text-state-red" style={{left:pct(runway.worst_delay_days)}}>▲</span></Tooltip>}{runway.delay_after_decision_days>0&&<Tooltip title="After the decision" content={`${runway.delay_after_decision_days}d delay`}><span tabIndex={0} className="absolute bottom-0 -translate-x-1/2 text-[13px] font-bold text-state-blue" style={{left:pct(runway.delay_after_decision_days)}}>○</span></Tooltip>}</div>{noDelay&&<p className="mt-1 text-[10px] text-muted-foreground">No delay expected</p>}</div><div className="text-right"><p className={`font-mono text-sm font-semibold ${runway.margin_after_decision_days<0?"text-state-red":""}`}>{signedDays(runway.margin_after_decision_days)}</p><Badge tone={runway.status==="breaks"?"red":runway.status==="resolved"?"blue":runway.status==="close"?"amber":"green"}>{runway.status}</Badge></div></div>}
function AtStakeCard({today}:{today:TodayData}){return <Card className="min-w-0 overflow-hidden"><div className="p-5 sm:p-6"><SectionHead title="What is at stake?" caption={today.at_stake.subtitle}/></div><div className="hidden lg:block"><table className="table-fixed"><colgroup><col className="w-24"/><col/><col className="w-36"/><col className="w-36"/><col className="w-36"/><col className="w-28"/></colgroup><thead><tr><th>Booking</th><th>Customer</th><th>Decision</th><th className="text-right">If nothing is done</th><th className="text-right">With the decision</th><th className="text-right">Avoided</th></tr></thead><tbody>{today.at_stake.rows.map(row=><StakeRow key={row.id} row={row}/>)}<tr><td colSpan={3} className="font-semibold">Total</td><td className="text-right">{eur(today.at_stake.total_stay_eur)}</td><td className="text-right">{eur(today.at_stake.total_action_eur)}</td><td className="text-right font-semibold">{eur(today.at_stake.total_avoided_eur)}</td></tr></tbody></table></div><div className="divide-y divide-border lg:hidden">{today.at_stake.rows.map(row=><StakeCard key={row.id} row={row}/>)}</div><p className="border-t border-border p-5 text-xs leading-5 text-muted-foreground">{today.at_stake.basis}</p></Card>}
function StakeRow({row}:{row:Stake}){const unpriced=/not priced/i.test(row.costs_basis);return <tr><td><Link to="/approvals" search={{booking:row.id}} className="font-mono font-semibold">{row.id}</Link></td><td className="truncate">{row.customer}</td><td><div className="flex flex-wrap gap-1"><Badge tone={toneFor(row.decision)}>{row.decision}</Badge>{row.breaks_date&&<Badge tone="red">misses date</Badge>}</div></td>{[row.stay_exposure_eur,row.action_exposure_eur,row.avoided_eur].map((value,index)=><td key={index} className={`text-right tabular-nums ${index===2?"font-semibold":""}`}>{unpriced?<Tooltip title="Cost basis" content={row.costs_basis}><span tabIndex={0}>—</span></Tooltip>:eur(value)}</td>)}</tr>}
function StakeCard({row}:{row:Stake}){const unpriced=/not priced/i.test(row.costs_basis);return <Link to="/approvals" search={{booking:row.id}} className="block p-5 transition-colors hover:bg-muted"><div className="flex justify-between gap-3"><div><p className="font-mono text-xs font-semibold">{row.id}</p><p className="mt-1 text-xs text-muted-foreground">{row.customer}</p></div><div className="flex flex-col items-end gap-1"><Badge tone={toneFor(row.decision)}>{row.decision}</Badge>{row.breaks_date&&<Badge tone="red">misses date</Badge>}</div></div><div className="mt-4 grid grid-cols-3 gap-2 text-[10px] text-muted-foreground">{[["Nothing",row.stay_exposure_eur],["Decision",row.action_exposure_eur],["Avoided",row.avoided_eur]].map(([label,value])=><span key={String(label)}>{label}<b className="mt-1 block text-foreground">{unpriced?"—":eur(value as number)}</b></span>)}</div></Link>}
function CustomersCard({today}:{today:TodayData}){return <Card className="overflow-hidden"><div className="p-5 sm:p-6"><SectionHead title="Who needs to hear from us?" caption={today.customers.subtitle}/></div><div className="divide-y divide-border">{today.customers.rows.map(row=><Link key={row.customer} to="/approvals" search={{booking:row.bookings[0]??""}} className="block px-5 py-4 transition-colors hover:bg-muted"><div className="flex justify-between gap-3"><p className="text-sm font-medium">{row.customer}</p>{row.breaks_date&&<Badge tone="red">date missed</Badge>}</div><div className="mt-2 flex flex-wrap gap-2">{row.bookings.map(id=><span key={id} className="font-mono text-[10px] font-semibold">{id}</span>)}<span className="text-xs text-muted-foreground">{row.drafts} {row.drafts===1?"draft":"drafts"} ready</span></div></Link>)}</div></Card>}
