import { useMemo, useState } from "react";
import { Cell, Bar, BarChart, CartesianGrid, LabelList, Pie, PieChart, ResponsiveContainer, Tooltip as ChartTooltip, XAxis, YAxis } from "recharts";
import { ArrowRight, Check, Clock3, FileText, ShieldAlert } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { Badge, Button, Card, Sheet } from "@/components/ui";
import { sourceName, stateLabel, toneFor } from "@/lib/presentation";
import { useApp } from "./app-context";
import type { RunData } from "@/lib/api";

type Shipment=RunData["shipments"][number];
export function StatCard({label,value,caption,fact,tone="neutral"}:{label:string;value:number;caption:string;fact:string;tone?:"neutral"|"green"|"amber"|"blue"|"red"}){return <Card className="p-5"><p className="stat-label">{label}</p><p className="mt-3 font-mono text-3xl font-semibold tabular-nums">{value}</p><p className="mt-2 truncate text-xs text-muted-foreground">{caption}</p><Badge tone={tone} className="mt-4 normal-case">{fact}</Badge></Card>}
export function SectionHead({title,caption}:{title:string;caption?:string}){return <div className="mb-4"><h2 className="text-sm font-semibold">{title}</h2>{caption&&<p className="mt-1 text-xs text-muted-foreground">{caption}</p>}</div>}
export function ModeBadge({mode}:{mode:string}){return <Badge tone={toneFor(mode)}>{mode}</Badge>}

export function OverviewPage(){const {run,workflow}=useApp();const onPlan=run.summary["no-action"];const total=run.summary.reroute+run.summary.hold+onPlan;const pie=[{name:"Reroute",value:run.summary.reroute,tone:"var(--state-blue)"},{name:"Hold",value:run.summary.hold,tone:"var(--state-amber)"},{name:"On plan",value:onPlan,tone:"var(--state-green)"}];const chart=run.shipments.map(s=>({id:s.id,slack:s.slack_days,delay:s.decision.delay_days,breach:s.decision.delay_days>s.slack_days?s.decision.delay_days:null}));const awaiting=run.shipments.reduce((n,s)=>n+s.drafts.length,0)+run.tms.writebacks.length+workflow.outputs_sample.length;return <div className="space-y-5"><div className="stat-grid"><StatCard label="Bookings read" value={run.tms.bookings_read} caption="Read from the demo connector" fact={`${run.tms.bookings_affected} affected`} tone="blue"/><StatCard label="Rerouted" value={run.summary.reroute} caption="Alternative route recommended" fact={`${run.summary.reroute} decisions`} tone="blue"/><StatCard label="Held" value={run.summary.hold} caption="No safer route inside constraints" fact={`${run.summary.hold} held`} tone="amber"/><StatCard label="On plan" value={onPlan} caption="No action recommended" fact={`${onPlan} unchanged`} tone="green"/></div>
 <div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><Card className="p-5"><SectionHead title="Board outcome" caption="Decision state across the board"/><div className="h-64"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={pie} dataKey="value" innerRadius={70} outerRadius={95} paddingAngle={3} stroke="none">{pie.map(x=><Cell key={x.name} fill={x.tone}/>)}</Pie><text x="50%" y="48%" textAnchor="middle" className="chart-total">{total}</text><text x="50%" y="57%" textAnchor="middle" className="chart-caption">bookings</text></PieChart></ResponsiveContainer></div><div className="flex justify-center gap-5">{pie.map(x=><div key={x.name} className="text-xs"><span className="mr-2 inline-block size-2 rounded-full" style={{backgroundColor:x.tone}}/>{x.name} <b>{x.value}</b> · {total?Math.round(x.value/total*100):0}%</div>)}</div></Card>
 <Card className="p-5"><SectionHead title="Schedule pressure" caption="Slack against disruption delay, in days"/><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart} margin={{top:20,right:10,left:-20,bottom:0}}><CartesianGrid vertical={false} stroke="var(--border)"/><XAxis dataKey="id" tick={{fontSize:10,fill:"var(--muted-foreground)"}} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} tick={{fontSize:10,fill:"var(--muted-foreground)"}} axisLine={false} tickLine={false}/><ChartTooltip cursor={{fill:"var(--muted)"}}/><Bar dataKey="slack" fill="var(--state-green-soft)" radius={[4,4,0,0]}/><Bar dataKey="delay" fill="var(--state-blue)" radius={[4,4,0,0]}><LabelList dataKey="breach" position="top" fill="var(--state-red)" fontSize={10}/></Bar></BarChart></ResponsiveContainer></div></Card></div>
 <div className="grid gap-5 xl:grid-cols-[1.4fr_.6fr]"><Card className="p-5"><SectionHead title="Active disruptions"/>{run.risk.events.length?run.risk.events.map(e=><div key={e.event_id} className="flex items-start gap-3 border-t border-border py-4 first:border-0 first:pt-0"><span className="mt-1 flex size-8 items-center justify-center rounded-lg bg-state-red-soft text-state-red"><ShieldAlert className="size-4"/></span><div className="min-w-0 flex-1"><p className="text-sm font-medium">{e.title}</p><p className="mt-1 text-xs text-muted-foreground">{sourceName(e.source)} · {e.chokepoint}</p></div><Badge tone={toneFor(e.severity)}>{e.severity}</Badge></div>):<p className="empty">Run a scenario to see disruptions here.</p>}</Card><Card className="p-5"><SectionHead title="Waiting for you"/><p className="font-mono text-4xl font-semibold">{awaiting}</p><p className="mt-2 text-xs text-muted-foreground">Drafts and queued write-backs</p><Link to="/approvals" className="mt-6 inline-flex items-center gap-2 text-sm font-medium">Review approvals <ArrowRight className="size-4"/></Link></Card></div>
 <Card className="p-4"><div className="flex flex-wrap gap-2">{run.workers.map(w=><span key={w.id} className="worker-pill"><span className={`size-1.5 rounded-full bg-state-${toneFor(w.mode)}`}/>{w.name}<ModeBadge mode={w.mode}/></span>)}</div></Card></div>}

export function ShipmentsPage(){const {run,approve,approved}=useApp();const [selected,setSelected]=useState<Shipment|null>(null);return <><Card className="overflow-hidden"><div className="p-5"><SectionHead title="Freight board" caption={`${run.shipments.length} bookings read from the demo connector`}/></div><div className="table-wrap"><table><thead><tr><th>ID</th><th>Cargo</th><th>Lane</th><th>Customer</th><th>Carrier</th><th>Slack</th><th>State</th></tr></thead><tbody>{run.shipments.map(s=><tr key={s.id} onClick={()=>setSelected(s)}><td className="font-mono">{s.id}</td><td className="font-medium">{s.cargo}</td><td>{s.origin} <ArrowRight className="mx-1 inline size-3"/> {s.final_destination}</td><td>{s.customer}</td><td>{s.carrier}</td><td>{s.slack_days}d</td><td><Badge tone={toneFor(s.state)}>{stateLabel(s.state)}</Badge></td></tr>)}</tbody></table></div></Card><Sheet open={!!selected} onOpenChange={o=>!o&&setSelected(null)} title={selected?.id??"Shipment"}>{selected&&<ShipmentDetail shipment={selected} approve={approve} approved={approved}/>}</Sheet></>}
function ShipmentDetail({shipment,approve,approved}:{shipment:Shipment;approve:(keys:string[])=>void;approved:Set<string>}){const {run}=useApp();const triggerIds:readonly string[]=shipment.decision.triggering_events;const event=run.risk.events.find(e=>triggerIds.includes(e.event_id));const writes=run.tms.writebacks.filter(w=>w.booking_ref===shipment.id);return <div className="space-y-6"><div><Badge tone={toneFor(shipment.state)}>{stateLabel(shipment.state)}</Badge><h3 className="mt-3 text-lg font-semibold">{shipment.decision.headline}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{shipment.decision.reasoning}</p></div><dl className="detail-grid"><div><dt>Decided by</dt><dd>{shipment.decision.decided_by}</dd></div><div><dt>Revised ETA</dt><dd>{shipment.decision.revised_eta}</dd></div><div><dt>Triggering event</dt><dd>{event?.title??"None"}</dd></div><div><dt>Booking reference</dt><dd className="font-mono">{shipment.booking_ref}</dd></div></dl><div><SectionHead title="Drafts"/>{shipment.drafts.length?shipment.drafts.map((d,i)=>{const key=`shipment-draft-${shipment.id}-${i}`;return <details key={key} className="detail-item"><summary><span><FileText className="size-4"/>{d.subject}</span><ChevronState/></summary><div className="mt-3 border-t border-border pt-3"><p className="mb-3 text-xs font-medium text-state-amber">Draft ready · waits for your approval</p><p className="whitespace-pre-line text-sm text-muted-foreground">{d.body}</p><Button className="mt-4" disabled={approved.has(key)} onClick={()=>approve([key])}><Check className="size-4"/>{approved.has(key)?"Approved":"Approve"}</Button></div></details>}):<p className="empty">Run a scenario to see decisions here.</p>}</div><div><SectionHead title="Queued TMS write-backs"/>{writes.map((w,i)=><div className="detail-item" key={`${w.operation}-${i}`}><div className="flex items-center justify-between"><span className="font-mono text-xs">{w.record}</span><Badge tone="blue">Queued — not written</Badge></div>{w.changes.map((c,j)=>{const from="from" in c?c.from:"—";return <p key={`${c.field}-${j}`} className="mt-2 text-sm"><span className="text-muted-foreground">{c.field}:</span> {from} <ArrowRight className="inline size-3"/> {c.to}</p>})}<p className="mt-2 text-xs text-muted-foreground">{w.agent}</p></div>)}</div></div>}
function ChevronState(){return <span className="text-xs text-muted-foreground">Open</span>}

export function RiskPage(){const {run}=useApp();const read=run.risk.live_sources_read,total=run.risk.live_sources_total;return <div className="space-y-5"><Card className="flex items-center justify-between p-5"><div><p className="stat-label">Source status</p><p className="mt-2 text-sm font-medium">{read} of {total} sources read</p></div><Badge tone={read>0?"green":"amber"}>{read>0?"live":"no live source"}</Badge></Card><Card className="p-5"><SectionHead title="Events" caption="Signals connected to the current board"/>{run.risk.events.length?run.risk.events.map(e=><article className="border-t border-border py-5 first:border-0 first:pt-0" key={e.event_id}><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-xs text-muted-foreground">{e.event_id}</p><h3 className="mt-1 text-sm font-semibold">{e.title}</h3></div><Badge tone={toneFor(e.severity)}>{e.severity}</Badge></div><div className="mt-4 flex flex-wrap gap-x-8 gap-y-2 text-xs text-muted-foreground"><span>Chokepoint <b className="text-foreground">{e.chokepoint}</b></span><span>Source <b className="text-foreground">{sourceName(e.source)}</b></span><span>Expected duration <b className="text-foreground">{e.expected_duration_hours.join("–")}h</b></span></div></article>):<p className="empty">Run a scenario to see disruptions here.</p>}</Card></div>}
