import { Link, useNavigate, useRouterState } from "@tanstack/react-router";
import { hostOf } from "@/lib/api";
import { Activity, Bell, Bot, House, LayoutDashboard, Map, Pencil, Plug, Sparkles, ChevronRight, CircleGauge, Command, Link2, Menu, Search, ShieldAlert, Ship, Trash2, X } from "lucide-react";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { CHAT_EVENT, deleteChat, loadChats, newChatId, type SavedChat } from "@/lib/chat-store";
import { waitingCount } from "@/lib/presentation";
import { Badge, Button } from "@/components/ui";
import { useApp } from "./app-context";

const nav=[
 {group:"",items:[{to:"/",label:"Home",icon:House},{to:"/dashboard",label:"Dashboard",icon:LayoutDashboard}]},
 {group:"Automation",items:[{to:"/desk",label:"Desk",icon:Activity},{to:"/approvals",label:"Approvals",icon:Bell},{to:"/tms",label:"TMS link",icon:Link2}]},
 {group:"Risk",items:[{to:"/map",label:"Map",icon:Map},{to:"/overview",label:"Board",icon:CircleGauge},{to:"/shipments",label:"Shipments",icon:Ship},{to:"/risk",label:"Risk feed",icon:ShieldAlert}]},
 {group:"System",items:[{to:"/connections",label:"Connections",icon:Plug},{to:"/agents",label:"Agents",icon:Bot}]},
] as const;
const pageCopy:Record<string,[string,string]>={"/ ":["Home","Ask the desk — every answer is checked against the board"],"/dashboard":["Dashboard","Operational insights counted from the current run"],"/connections":["Connections","Every source and destination connected to the desk"],"/map":["Map","Every booking monitored through the TMS link"],"/overview":["Board","Decisions across the active freight board"],"/shipments":["Shipments","Every booking, decision and approval gate"],"/desk":["Desk","The everyday inbox worked by the agent team"],"/risk":["Risk feed","The disruption signals behind each decision"],"/approvals":["Approvals","Drafts and queued changes waiting for you"],"/agents":["Agents","The people-free operating layers behind the board"],"/tms":["TMS link","A transparent view of the demo connector queue"]};
export function AppShell({children}:{children:ReactNode}){
 const {run,workflow,recorded,loading,selectedScenario,setSelectedScenario,executeRun,approved,connection}=useApp();const navigate=useNavigate(); const path=useRouterState({select:s=>s.location.pathname});
 const [mobile,setMobile]=useState(false);const [palette,setPalette]=useState(false);const [query,setQuery]=useState("");const [chats,setChats]=useState<SavedChat[]>([]);const awaiting=waitingCount(run,workflow)-approved.size;
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setPalette(true)}};addEventListener("keydown",fn);return()=>removeEventListener("keydown",fn)},[]);
 useEffect(()=>{const refresh=()=>setChats(loadChats());refresh();addEventListener(CHAT_EVENT,refresh);return()=>removeEventListener(CHAT_EVENT,refresh)},[path]);
 const bookings=useMemo(()=>run.shipments.map(s=>({to:"/shipments" as const,label:`${s.id} · ${s.cargo}`})),[run]);
 const searchResults=useMemo(()=>[...nav.flatMap(g=>g.items.map(i=>({to:i.to,label:i.label}))),...bookings].filter(x=>x.label.toLowerCase().includes(query.toLowerCase())),[bookings,query]);
 const banner=honestyLine(run,connection);function askFromPalette(){const q=query.trim();if(!q)return;const id=newChatId();setPalette(false);setQuery("");void navigate({to:"/",search:{q,chat:id}})}
 const title=pageCopy[path===`/`?"/ ":path]??["SQRlane","Freight operations"];
 return <div className="min-h-screen bg-background text-foreground"><div className="honesty" title={banner}><span>{banner}</span></div>
 <aside className={`sidebar ${mobile?"sidebar-open":""}`}><div className="flex h-16 items-center justify-between px-5"><Link to="/" className="flex items-center gap-2 text-lg font-semibold"><span className="size-3 bg-primary"/>SQRlane</Link><Button variant="ghost" className="size-8 p-0 lg:hidden" onClick={()=>setMobile(false)}><X className="size-4"/></Button></div>
 <div className="mx-4 grid grid-cols-[minmax(0,1fr)_auto] gap-2"><Button variant="outline" className="min-w-0 justify-start px-3 text-muted-foreground" onClick={()=>setPalette(true)}><Search className="size-4"/><span className="flex-1 text-left">Search</span><kbd>⌘K</kbd></Button><Button variant="outline" className="size-9 p-0" aria-label="New chat" title="New chat" onClick={()=>{const id=newChatId();setMobile(false);void navigate({to:"/",search:{chat:id}})}}><Pencil className="size-4"/></Button></div>
 <nav className="mt-6 flex-1 overflow-y-auto px-3">{nav.map(group=><div key={group.group} className="mb-5">{group.group&&<p className="px-2 pb-2 text-[10px] font-semibold uppercase text-muted-foreground">{group.group}</p>}{group.items.map(item=>{const Icon=item.icon;const count=item.label==="Shipments"?run.shipments.length:item.label==="Desk"?workflow.items.length:item.label==="Approvals"?awaiting:undefined;return <div key={item.to}><Link to={item.to} onClick={()=>setMobile(false)} activeOptions={{exact:item.to==="/"}} className="nav-link" activeProps={{className:"nav-link nav-link-active"}}><Icon className="size-4"/><span>{item.label}</span>{count!==undefined&&<span className="ml-auto tabular-nums">{count}</span>}</Link>{item.to==="/"&&chats.length>0&&<div className="mb-3 mt-2"><p className="px-2 pb-1 text-[10px] font-semibold uppercase text-muted-foreground">Recent</p>{chats.map(chat=><div key={chat.id} className="group/chat grid grid-cols-[minmax(0,1fr)_auto] items-center"><Link to="/" search={{chat:chat.id}} onClick={()=>setMobile(false)} className="truncate rounded-md px-2 py-1.5 text-xs text-muted-foreground hover:bg-muted hover:text-foreground">{chat.title}</Link><Button variant="ghost" className="size-7 p-0 opacity-0 group-hover/chat:opacity-100 focus:opacity-100" aria-label={`Delete ${chat.title}`} onClick={()=>deleteChat(chat.id)}><Trash2 className="size-3"/></Button></div>)}</div>}</div>})}</div>)}</nav>
 <div className="border-t border-border px-5 py-4 text-xs text-muted-foreground"><div className="mb-1 flex items-center gap-2"><span className="size-1.5 rounded-full bg-state-green"/>Decision engine</div><span className="font-mono">{run.ai?.model??"rules"}</span></div></aside>
   <div className="lg:pl-[248px]"><PageHeader title={title} run={run} selectedScenario={selectedScenario} setSelectedScenario={setSelectedScenario} recorded={recorded} awaiting={awaiting} loading={loading} executeRun={executeRun} openMenu={()=>setMobile(true)}/>
 <main className="mx-auto max-w-[1520px] p-4 md:p-6">{loading?<><RunProgress/><ContentSkeleton/></>:children}</main></div>
  {palette&&<div className="fixed inset-0 z-[70] bg-overlay p-4 pt-[12vh]" onMouseDown={()=>setPalette(false)}><div className="mx-auto max-w-lg overflow-hidden rounded-xl border border-border bg-card shadow-drawer" onMouseDown={e=>e.stopPropagation()}><div className="flex items-center gap-3 border-b border-border px-4"><Command className="size-4 text-muted-foreground"/><input autoFocus value={query} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();askFromPalette()}}} onChange={e=>setQuery(e.target.value)} className="h-12 min-w-0 flex-1 bg-transparent text-sm outline-none" placeholder="Ask the desk, or search views and bookings"/></div><div className="max-h-96 overflow-y-auto p-2">{query.trim()&&<button onClick={askFromPalette} className="flex w-full items-center gap-2 rounded-md bg-muted px-3 py-2 text-left text-sm"><Sparkles className="size-3.5 shrink-0"/><span className="min-w-0 truncate">Ask SQRlane: {query.trim()}</span></button>}<p className="px-2 py-2 text-[10px] font-semibold uppercase text-muted-foreground">Views & bookings</p>{searchResults.map((x,i)=><Link key={`${x.label}-${i}`} to={x.to} onClick={()=>{setPalette(false);setQuery("")}} className="flex items-center justify-between rounded-md px-3 py-2 text-sm hover:bg-muted"><span>{x.label}</span><ChevronRight className="size-3.5 text-muted-foreground"/></Link>)}{!searchResults.length&&!query.trim()&&<p className="empty">No matching view or booking.</p>}</div></div></div>}</div>
}
function PageHeader({title,run,selectedScenario,setSelectedScenario,recorded,awaiting,loading,executeRun,openMenu}:{title:[string,string];run:ReturnType<typeof useApp>["run"];selectedScenario:ReturnType<typeof useApp>["selectedScenario"];setSelectedScenario:ReturnType<typeof useApp>["setSelectedScenario"];recorded:boolean;awaiting:number;loading:boolean;executeRun:()=>Promise<void>;openMenu:()=>void}){return <header className="topbar"><div className="flex min-w-0 items-center gap-3"><Button variant="ghost" className="size-9 shrink-0 p-0 lg:hidden" onClick={openMenu}><Menu className="size-4"/></Button><div className="min-w-0"><h1 className="truncate text-xl font-semibold">{title[0]}</h1><p className="mt-0.5 truncate text-xs text-muted-foreground">{title[1]}</p></div></div><div className="topbar-actions"><div className="hidden items-center rounded-lg bg-muted p-1 xl:flex">{run.scenarios.map(s=><Button key={s.id} variant="ghost" className={`scenario-option ${selectedScenario===s.id?"scenario-option-active":""}`} onClick={()=>setSelectedScenario(s.id)}>{s.name}</Button>)}</div>{recorded&&<Badge tone="amber">Showing a recorded run</Badge>}<Link to="/approvals" className="relative flex size-9 shrink-0 items-center justify-center rounded-lg border border-border bg-card" aria-label="Approvals"><Bell className="size-4"/>{awaiting>0&&<span className="absolute right-1.5 top-1.5 size-1.5 rounded-full bg-state-red"/>}</Link><Button disabled={loading} onClick={executeRun}><span className="hidden sm:inline">{loading?"Running…":"Run scenario"}</span><span className="sm:hidden">{loading?"…":"Run"}</span><ChevronRight className="size-4"/></Button></div><p className="last-run">{run.ran_at?`Last run ${new Date(run.ran_at).toLocaleString([], {dateStyle:"medium",timeStyle:"short"})}`:"Not run yet"}</p></header>}
function RunProgress(){const {progress}=useApp();const labels=["Reading sources","Deciding","Drafting","Queuing to the TMS"];return <div className="mb-5 rounded-xl border border-border bg-card p-4"><div className="mb-3 flex gap-2 text-xs text-muted-foreground">{labels.map((x,i)=><span key={x} className={i<progress?"text-foreground":""}>{x}{i<3&&" · "}</span>)}</div><div className="h-1 overflow-hidden rounded-full bg-muted"><div className="h-full animate-progress bg-state-blue"/></div></div>}
function ContentSkeleton(){return <div aria-label="Loading scenario results" className="space-y-5"><div className="stat-grid">{[0,1,2,3].map(x=><div key={x} className="h-40 rounded-xl border border-border bg-card p-5"><div className="skeleton h-3 w-24 rounded"/><div className="skeleton mt-5 h-9 w-12 rounded"/><div className="skeleton mt-4 h-3 w-36 rounded"/></div>)}</div><div className="grid gap-5 xl:grid-cols-2"><div className="skeleton h-80 rounded-xl"/><div className="skeleton h-80 rounded-xl"/></div></div>}

function honestyLine(run:ReturnType<typeof useApp>["run"],connection:ReturnType<typeof useApp>["connection"]){
 if(!connection)return "The risk detection is real — shipments are synthetic, so a disruption can be shown on demand. The TMS link is a demo connector: nothing is sent and nothing is written.";
 const h=(run.tms as {honesty?:string}).honesty; if(h&&!/demo connector/i.test(h))return h;
 const host=hostOf(connection.writeback_url);
 return `Bookings come from your TMS (${connection.source}), ${connection.kind==="api"?"read live from its endpoint":"read from your export"}. The risk detection is real. Every change waits for your approval${host?` — then it is sent to ${host}`:" and is exported for you to import"}.`;
}
