import { Link, useRouterState } from "@tanstack/react-router";
import { Activity, Bell, Bot, ChevronRight, CircleGauge, Command, Link2, Menu, Search, ShieldAlert, Ship, X } from "lucide-react";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { waitingCount } from "@/lib/presentation";
import { Badge, Button } from "@/components/ui";
import { useApp } from "./app-context";

const nav=[
 {group:"Overview",items:[{to:"/",label:"Overview",icon:CircleGauge}]},
 {group:"Operations",items:[{to:"/shipments",label:"Shipments",icon:Ship},{to:"/desk",label:"Desk",icon:Activity},{to:"/risk",label:"Risk feed",icon:ShieldAlert},{to:"/approvals",label:"Approvals",icon:Bell}]},
 {group:"System",items:[{to:"/agents",label:"Agents",icon:Bot},{to:"/tms",label:"TMS link",icon:Link2}]},
] as const;
const pageCopy:Record<string,[string,string]>={"/ ":["Overview","Decisions across the active freight board"],"/shipments":["Shipments","Every booking, decision and approval gate"],"/desk":["Desk","The everyday inbox worked by the agent team"],"/risk":["Risk feed","The disruption signals behind each decision"],"/approvals":["Approvals","Drafts and queued changes waiting for you"],"/agents":["Agents","The people-free operating layers behind the board"],"/tms":["TMS link","A transparent view of the demo connector queue"]};
export function AppShell({children}:{children:ReactNode}){
 const {run,workflow,recorded,loading,selectedScenario,setSelectedScenario,executeRun,approved}=useApp(); const path=useRouterState({select:s=>s.location.pathname});
 const [mobile,setMobile]=useState(false);const [palette,setPalette]=useState(false);const [query,setQuery]=useState("");const awaiting=waitingCount(run,workflow)-approved.size;
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setPalette(true)}};addEventListener("keydown",fn);return()=>removeEventListener("keydown",fn)},[]);
 const bookings=useMemo(()=>run.shipments.map(s=>({to:"/shipments" as const,label:`${s.id} · ${s.cargo}`})),[run]);
 const searchResults=useMemo(()=>[...nav.flatMap(g=>g.items.map(i=>({to:i.to,label:i.label}))),...bookings].filter(x=>x.label.toLowerCase().includes(query.toLowerCase())),[bookings,query]);
 const title=pageCopy[path===`/`?"/ ":path]??["SQRlane","Freight operations"];
 return <div className="min-h-screen bg-background text-foreground"><div className="honesty">The risk detection is real — shipments are synthetic, so a disruption can be shown on demand. The TMS link is a demo connector: nothing is sent and nothing is written.</div>
 <aside className={`sidebar ${mobile?"sidebar-open":""}`}><div className="flex h-16 items-center justify-between px-5"><Link to="/" className="flex items-center gap-2 text-lg font-semibold"><span className="size-3 bg-primary"/>SQRlane</Link><Button variant="ghost" className="size-8 p-0 lg:hidden" onClick={()=>setMobile(false)}><X className="size-4"/></Button></div>
 <Button variant="outline" className="mx-4 w-[calc(100%-2rem)] justify-start px-3 text-muted-foreground" onClick={()=>setPalette(true)}><Search className="size-4"/><span className="flex-1 text-left">Search</span><kbd>⌘K</kbd></Button>
 <nav className="mt-6 flex-1 overflow-y-auto px-3">{nav.map(group=><div key={group.group} className="mb-5"><p className="px-2 pb-2 text-[10px] font-semibold uppercase text-muted-foreground">{group.group}</p>{group.items.map(item=>{const Icon=item.icon;const count=item.label==="Shipments"?run.shipments.length:item.label==="Desk"?workflow.items.length:item.label==="Approvals"?awaiting:undefined;return <Link key={item.to} to={item.to} onClick={()=>setMobile(false)} activeOptions={{exact:item.to==="/"}} className="nav-link" activeProps={{className:"nav-link nav-link-active"}}><Icon className="size-4"/><span>{item.label}</span>{count!==undefined&&<span className="ml-auto tabular-nums">{count}</span>}</Link>})}</div>)}</nav>
 <div className="border-t border-border px-5 py-4 text-xs text-muted-foreground"><div className="mb-1 flex items-center gap-2"><span className="size-1.5 rounded-full bg-state-green"/>Decision engine</div><span className="font-mono">{run.ai.model??"rules"}</span></div></aside>
 <div className="lg:pl-[248px]"><header className="topbar"><div className="flex items-center gap-3"><Button variant="ghost" className="size-9 p-0 lg:hidden" onClick={()=>setMobile(true)}><Menu className="size-4"/></Button><div><h1 className="text-xl font-semibold">{title[0]}</h1><p className="mt-0.5 text-xs text-muted-foreground">{title[1]}</p></div></div><div className="topbar-actions"><div className="hidden items-center rounded-lg bg-muted p-1 xl:flex">{run.scenarios.map(s=><Button key={s.id} variant="ghost" className={`scenario-option ${selectedScenario===s.id?"scenario-option-active":""}`} onClick={()=>setSelectedScenario(s.id)}>{s.name}</Button>)}</div>{recorded&&<Badge tone="amber">Showing a recorded run</Badge>}<Link to="/approvals" className="relative flex size-9 shrink-0 items-center justify-center rounded-lg border border-border bg-card" aria-label="Approvals"><Bell className="size-4"/>{awaiting>0&&<span className="absolute right-1.5 top-1.5 size-1.5 rounded-full bg-state-red"/>}</Link><Button disabled={loading} onClick={executeRun}><span className="hidden sm:inline">{loading?"Running…":"Run scenario"}</span><span className="sm:hidden">{loading?"…":"Run"}</span><ChevronRight className="size-4"/></Button></div><p className="last-run">Last run {new Date(run.ran_at).toLocaleString([], {dateStyle:"medium",timeStyle:"short"})}</p></header>
 <main className="mx-auto max-w-[1520px] p-4 md:p-6">{loading?<><RunProgress/><ContentSkeleton/></>:children}</main></div>
 {palette&&<div className="fixed inset-0 z-[70] bg-overlay p-4 pt-[12vh]" onMouseDown={()=>setPalette(false)}><div className="mx-auto max-w-lg overflow-hidden rounded-xl border border-border bg-card shadow-drawer" onMouseDown={e=>e.stopPropagation()}><div className="flex items-center gap-3 border-b border-border px-4"><Command className="size-4 text-muted-foreground"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} className="h-12 flex-1 bg-transparent text-sm outline-none" placeholder="Search views and bookings"/></div><div className="max-h-96 overflow-y-auto p-2"><p className="px-2 py-2 text-[10px] font-semibold uppercase text-muted-foreground">Views & bookings</p>{searchResults.map((x,i)=><Link key={`${x.label}-${i}`} to={x.to} onClick={()=>{setPalette(false);setQuery("")}} className="flex items-center justify-between rounded-md px-3 py-2 text-sm hover:bg-muted"><span>{x.label}</span><ChevronRight className="size-3.5 text-muted-foreground"/></Link>)}{!searchResults.length&&<p className="empty">No matching view or booking.</p>}</div></div></div>}</div>
}
function RunProgress(){const {progress}=useApp();const labels=["Reading sources","Deciding","Drafting","Queuing to the TMS"];return <div className="mb-5 rounded-xl border border-border bg-card p-4"><div className="mb-3 flex gap-2 text-xs text-muted-foreground">{labels.map((x,i)=><span key={x} className={i<progress?"text-foreground":""}>{x}{i<3&&" · "}</span>)}</div><div className="h-1 overflow-hidden rounded-full bg-muted"><div className="h-full animate-progress bg-state-blue"/></div></div>}
function ContentSkeleton(){return <div aria-label="Loading scenario results" className="space-y-5"><div className="stat-grid">{[0,1,2,3].map(x=><div key={x} className="h-40 rounded-xl border border-border bg-card p-5"><div className="skeleton h-3 w-24 rounded"/><div className="skeleton mt-5 h-9 w-12 rounded"/><div className="skeleton mt-4 h-3 w-36 rounded"/></div>)}</div><div className="grid gap-5 xl:grid-cols-2"><div className="skeleton h-80 rounded-xl"/><div className="skeleton h-80 rounded-xl"/></div></div>}
