import * as Dialog from "@radix-ui/react-dialog";
import * as TooltipPrimitive from "@radix-ui/react-tooltip";
import { X } from "lucide-react";
import type { ButtonHTMLAttributes, ReactNode } from "react";
import { cn } from "@/lib/utils";

export function Button({ className, variant = "primary", ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "outline" | "ghost" }) {
  return <button className={cn("inline-flex h-9 items-center justify-center gap-2 rounded-lg px-3 text-sm font-medium transition-colors disabled:pointer-events-none disabled:opacity-45", variant === "primary" && "bg-primary text-primary-foreground hover:bg-primary/90", variant === "outline" && "border border-border bg-card text-foreground hover:bg-muted", variant === "ghost" && "text-muted-foreground hover:bg-muted hover:text-foreground", className)} {...props} />;
}
export function Card({ className, children }: { className?: string; children: ReactNode }) { return <section className={cn("rounded-xl border border-border bg-card", className)}>{children}</section>; }
export function Badge({ children, tone = "neutral", className }: { children: ReactNode; tone?: "green" | "amber" | "blue" | "red" | "neutral"; className?: string }) { return <span className={cn("inline-flex h-5 shrink-0 items-center rounded-full px-2 text-[10px] font-semibold uppercase", `badge-${tone}`, className)}>{children}</span>; }
export function Sheet({ open, onOpenChange, title, children }: { open: boolean; onOpenChange: (open: boolean) => void; title: string; children: ReactNode }) {
 return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-overlay data-[state=open]:animate-in data-[state=closed]:animate-out"/><Dialog.Content className="fixed inset-y-0 right-0 z-50 w-full max-w-xl overflow-y-auto border-l border-border bg-background p-6 shadow-drawer data-[state=open]:animate-in data-[state=open]:slide-in-from-right data-[state=closed]:animate-out data-[state=closed]:slide-out-to-right"><div className="mb-6 flex items-start justify-between gap-4"><Dialog.Title className="text-xl font-semibold">{title}</Dialog.Title><Dialog.Close asChild><Button variant="ghost" className="size-10 p-0" aria-label="Close"><X className="size-4"/></Button></Dialog.Close></div>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>;
}
export function Tooltip({ content, children, title = "Why" }: { content: ReactNode; children: ReactNode; title?: string }) { return <TooltipPrimitive.Provider delayDuration={150}><TooltipPrimitive.Root><TooltipPrimitive.Trigger asChild>{children}</TooltipPrimitive.Trigger><TooltipPrimitive.Portal><TooltipPrimitive.Content sideOffset={6} className="z-[60] max-w-xs rounded-md bg-tooltip px-3 py-2 text-xs text-tooltip-foreground shadow-lg"><strong className="mb-1 block">{title}</strong>{content}<TooltipPrimitive.Arrow className="fill-tooltip"/></TooltipPrimitive.Content></TooltipPrimitive.Portal></TooltipPrimitive.Root></TooltipPrimitive.Provider>; }
